2020-08-20 18:56:59,891 ERROR: Exception on /auth/reset_password_request [POST] [in c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Stan\Desktop\dev\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Stan\Desktop\dev\microblog\app\auth\email.py", line 12, in send_password_reset_email
    user=user, token =token),
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Stan\Desktop\dev\microblog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-08-20 18:57:24,230 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:74]
2020-08-20 18:57:37,703 ERROR: Exception on /auth/reset_password_request [POST] [in c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Stan\Desktop\dev\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Stan\Desktop\dev\microblog\app\auth\email.py", line 12, in send_password_reset_email
    user=user, token =token),
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Stan\Desktop\dev\microblog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\stan\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-08-20 18:58:25,629 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:74]
2020-08-30 18:25:58,967 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:77]
2020-08-30 18:26:40,637 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:77]
2020-08-30 19:19:35,297 INFO: Microblog startup [in C:\Users\Stan\Desktop\dev\microblog\app\__init__.py:77]
